version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR and Docker Hub 
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 121802605768.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image
      - docker build --no-cache -t tomcat-jsp-repo .
      - docker tag tomcat-jsp-repo:latest 121802605768.dkr.ecr.us-east-1.amazonaws.com/tomcat-jsp-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR and Docker Hub
      - docker push 121802605768.dkr.ecr.us-east-1.amazonaws.com/tomcat-jsp-repo:latest
      - printf '[{"name":"tomcat","imageUri":"%s"}]' 121802605768.dkr.ecr.us-east-1.amazonaws.com/tomcat-jsp-repo:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
